Repository bengibaykal/swe574group1, pull requests merged in 2020-06, with the labels that each got.

#130 Comment length changed from 30 to 250
  cityapp/templates/user/post.html
Labels: Frontend, Priority : Critical

#138 Date added to the comments
  cityapp/templates/user/post.html
Labels: Frontend

#139 show annotations closes #99
  cityapp/templates/user/manager.html
Labels: Backend, Frontend, annotation

#140 Post and desrciption added to manager.py
  cityapp/templates/user/manager.html
Labels: Frontend
