Repository bengibaykal/swe574group1, pull requests merged in 2020-05, with the labels that each got.

#86 Feature/create new city
  cityapp/api/city_view.py
  cityapp/city/__init__.py
  cityapp/city/admin.py
  cityapp/city/apps.py
  cityapp/city/migrations/0001_initial.py
  cityapp/city/migrations/0002_auto_20200427_1430.py
  cityapp/city/migrations/0003_auto_20200501_0751.py
  cityapp/city/migrations/__init__.py
  cityapp/city/models.py
  cityapp/city/serializers.py
  cityapp/city/tests.py
  cityapp/city/urls.py
  cityapp/city/views.py
  cityapp/cityapp/settings.py
  cityapp/community/migrations/0026_community_city_id.py
  cityapp/community/migrations/0027_auto_20200510_1333.py
  cityapp/community/migrations/0030_merge_20200517_0945.py
  cityapp/community/models.py
  cityapp/community/views.py
  cityapp/templates/user/cards.html
  cityapp/templates/user/cities.html
  cityapp/templates/user/city.html
  cityapp/templates/user/create_city.html
  cityapp/templates/user/manager.html
Labels: Priority : Medium, Type : Development

#93 Bug/builder id city creation
  cityapp/city/models.py
  cityapp/city/views.py
  cityapp/templates/user/cities.html
  cityapp/templates/user/communities.html
Labels: Backend, Frontend, Priority : Critical

#88 Feature/display city column
  cityapp/cityapp/settings.py
Labels: Frontend

#96 /cities/detail changed to city/detail, URL bug fixed
  cityapp/templates/user/create_city.html
Labels: Frontend

#106 Feature/select city in community creation
  cityapp/city/migrations/0009_merge_20200518_1844.py
  cityapp/city/urls.py
  cityapp/city/views.py
  cityapp/cityapp/settings.py
  cityapp/community/views.py
  cityapp/templates/user/create_community.html
Labels: Backend, Frontend, Priority : Medium

#117 Feature/comment fe
  cityapp/api/community_view.py
  cityapp/api/urls.py
  cityapp/city/migrations/0009_merge_20200531_1144.py
  cityapp/city/migrations/0010_merge_20200531_1618.py
  cityapp/community/migrations/0031_auto_20200531_1144.py
  cityapp/community/migrations/0032_auto_20200531_1231.py
  cityapp/community/migrations/0037_merge_20200531_1619.py
  cityapp/community/migrations/0038_auto_20200531_1619.py
  cityapp/community/urls.py
  cityapp/community/views.py
  cityapp/templates/user/post.html
Labels: Frontend, Priority : High

#122 Country Autofill Added
  cityapp/templates/user/create_city.html
Labels: Backend, Frontend

#125 Bug reading descriptions of posts solved
  cityapp/templates/user/manager.html
Labels: Backend

#129 image crop site-statics closes #128
  cityapp/site_static/js/jquery.Jcrop.js
  cityapp/site_static/js/jquery.Jcrop.min.js
  cityapp/site_static/js/jquery.color.js
  cityapp/site_static/js/jquery.min.js
Labels: Frontend

#127 Feature/annotation backend
  cityapp/annotations/__init__.py
  cityapp/annotations/admin.py
  cityapp/annotations/api/__init__.py
  cityapp/annotations/api/serializers.py
  cityapp/annotations/api/urls.py
  cityapp/annotations/api/views.py
  cityapp/annotations/apps.py
  cityapp/annotations/models.py
  cityapp/annotations/schemas.py
  cityapp/annotations/tests.py
  cityapp/annotations/urls.py
  cityapp/annotations/validators.py
  cityapp/annotations/views.py
  cityapp/templates/user/manager.html
Labels: Backend, annotation
